# Generated by Django 4.1.7 on 2023-02-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsblog_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={},
        ),
    ]
