# Generated by Django 4.1.7 on 2023-02-18 19:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("newsblog_app", "0002_alter_blog_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"permissions": [("edit_own_blog", "Can edit own blog")]},
        ),
    ]
