# Generated by Django 4.1.7 on 2023-02-19 07:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("newsblog_app", "0003_alter_blog_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "permissions": [
                    ("edit_own_blog", "Can edit own blog"),
                    ("delete_own_blog", "Can delete own blog"),
                ]
            },
        ),
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
